AWS_ACCESS_KEY_ID = 'REDACTED'
AWS_ENDPOINT = 'REDACTED'
AWS_SECRET_ACCESS_KEY = 'REDACTED'
AWS_REGION = 'REDACTED'
AWS_S3_BUCKET_NAME = 'my_bucket'


LOG_FILE = '/var/log/crowdai/crowdai-grader.log'
LOG_BYTES_PER_FILE = 1048576

FLASK_PORT = 1000
FLASK_PROCESSES = 12
